ARCHS = armv7 armv7s arm64 arm64e

MODULES = jailed
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AppCake2
DISPLAY_NAME = AppCake++
BUNDLE_ID = io.crafterpika.appcakepp2

AppCake2_FILES = Tweak.xm
AppCake2_IPA = ./appcake_7.1.0.ipa

include $(THEOS_MAKE_PATH)/tweak.mk
